# Restructuring Data into Tidy Form

## 정돈된 형태로 데이터 재구성 



## 8.4 스택된 데이터 되돌리기 

- Dataframe 은 두 가지 유사한 메서드인 stack 과 melt 가 있어서 수평 열 이름을 수직 열 값으로 변환할 수 있다. DataFrame 은 이 두 연산을 각각 unstack 과 pivot 메서드를 사용해 되돌릴 수 있다. 
- stack/unstack : melt/pivot 보다 더 단순한 메서드로 열/행 인덱스에 대해서만 조절한다
- melt/pivot : 어떤 열을 재구성할 것인지 선택할 수 있어 보다 더 많은 유연성을 가질 수 있다.

### 준비 단계

이 단계에서는 데이터셋을 stack/melt 한 후 unstack/pivot 을 사용해 즉시 원래 상태로 되돌린다.

### 방법

In [1]:
import pandas as pd
path = 'C:/Users/HS/Documents/GitHub/Python-Study/Pandas-Cookbook/data'

In [11]:
# 1. college 데이터셋을 기관명을 인덱스로 설정하고 학부생 인종 열 그룹만 읽어들인다. 
usecol_func = lambda x: 'UGDS_' in x or x == 'INSTNM'

college = pd.read_csv(path + '/college.csv', 
                      index_col = 'INSTNM',    # index_col : 인덱스로 사용할 열(기관명)
                      usecols = usecol_func)   # usecols : 사용할 열만 불러들이기(인종열)
college.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

In [6]:
# 2. stack 메서드를 사용해 각 수평 열을 수직 인덱스 레벨로 변환한다. 

college_stacked = college.stack()
college_stacked.head(18)

INSTNM
Alabama A & M University             UGDS_WHITE    0.0333
                                     UGDS_BLACK    0.9353
                                     UGDS_HISP     0.0055
                                     UGDS_ASIAN    0.0019
                                     UGDS_AIAN     0.0024
                                     UGDS_NHPI     0.0019
                                     UGDS_2MOR     0.0000
                                     UGDS_NRA      0.0059
                                     UGDS_UNKN     0.0138
University of Alabama at Birmingham  UGDS_WHITE    0.5922
                                     UGDS_BLACK    0.2600
                                     UGDS_HISP     0.0283
                                     UGDS_ASIAN    0.0518
                                     UGDS_AIAN     0.0022
                                     UGDS_NHPI     0.0007
                                     UGDS_2MOR     0.0368
                                     UGDS_NRA      0.0179
                                     UGDS_UNKN     0.0100
dtype: float64

In [10]:
# 3. 이 스택된 데이터를 unstack Series 메서드를 사용해 원래 형태로 되돌린다. 
college_stacked.unstack().head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

In [13]:
# 4. melt 와 pivot 을 순서대로 사용해 비슷한 연산을 사용할 수 있다. 먼저 인덱스 기관 이름을 사용하지 않고 데이터를 읽어들인다. 

college2 = pd.read_csv(path + '/college.csv', 
                     usecols = usecol_func)
college2.head()

,INSTNM,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
0,Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
1,University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
2,Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
3,University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
4,Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

In [19]:
# melt 메서드를 써서 모든 인종 열을 단일 열로 전치한다.
college_melted = college2.melt(id_vars = 'INSTNM', 
                                 var_name = 'Race',
                                 value_name = 'Percentage')
college_melted

,INSTNM,Race,Percentage
0,Alabama A & M University,UGDS_WHITE,0.0333
1,University of Alabama at Birmingham,UGDS_WHITE,0.5922
2,Amridge University,UGDS_WHITE,0.2990
3,University of Alabama in Huntsville,UGDS_WHITE,0.6988
4,Alabama State University,UGDS_WHITE,0.0158
5,The University of Alabama,UGDS_WHITE,0.7825
6,Central Alabama Community College,UGDS_WHITE,0.7255
7,Athens State University,UGDS_WHITE,0.7823
8,Auburn University at Montgomery,UGDS_WHITE,0.5328
9,Auburn University,UGDS_WHITE,0.8507
10,Birmingham Southern College,UGDS_WHITE,0.7983
11,Chattahoochee Valley Community College,UGDS_WHITE,0.4661
12,Concordia College Alabama,UGDS_WHITE,0.0280
13,South University-Montgomery,UGDS_WHITE,0.3046
14,Enterprise State Community College,UGDS_WHITE,0.6408
15,James H Faulkner State Community College,UGDS_WHITE,0.6979
16,Faulkner University,UGDS_WHITE,0.3874
17,Gadsden State Community College,UGDS_WHITE,0.6921
18,New Beginning College of Cosmetology,UGDS_WHITE,0.8957
19,George C Wallace State Community College-Dothan,UGDS_WHITE,0.6273
20,George C Wallace State Community College-Hance...,UGDS_WHITE,0.8630
21,George C Wallace State Community College-Selma,UGDS_WHITE,0.1956
22,Herzing University-Birmingham,UGDS_WHITE,0.3543
23,Huntingdon College,UGDS_WHITE,0.6388
24,Heritage Christian University,UGDS_WHITE,0.7419
25,J F Drake State Community and Technical College,UGDS_WHITE,0.3337
26,Jacksonville State University,UGDS_WHITE,0.6834
27,Jefferson Davis Community College,UGDS_WHITE,0.5857
28,Jefferson State Community College,UGDS_WHITE,0.6696
29,John C Calhoun State Community College,UGDS_WHITE,0.6528
...,...,...,...
67785,Strayer University-Lawrenceville,UGDS_UNKN,NaN
67786,Strayer University-Piscataway,UGDS_UNKN,NaN
67787,Utah County Campus,UGDS_UNKN,NaN
67788,L'esprit Academy - Royal Oak,UGDS_UNKN,NaN
67789,National Career Institute - Jersey City Branch,UGDS_UNKN,NaN
67790,Strayer University-Cobb Campus,UGDS_UNKN,NaN
67791,Strayer University-Morrow Campus,UGDS_UNKN,NaN
67792,Strayer University-Roswell Campus,UGDS_UNKN,NaN
67793,Strayer University-Douglasville Campus,UGDS_UNKN,NaN
67794,Strayer University-Lithonia Campus,UGDS_UNKN,NaN
67795,Strayer University-Savannah Campus,UGDS_UNKN,NaN
67796,Strayer University-Augusta Campus,UGDS_UNKN,NaN
67797,Strayer University-Columbus,UGDS_UNKN,NaN
67798,Strayer University-Columbia Campus,UGDS_UNKN,NaN
67799,Strayer University-Charleston Campus,UGDS_UNKN,NaN
67800,Strayer University-Irving,UGDS_UNKN,NaN
67801,Strayer University-Katy,UGDS_UNKN,NaN
67802,Strayer University-Northwest Houston,UGDS_UNKN,NaN
67803,Strayer University-Plano,UGDS_UNKN,NaN
67804,Strayer University-Cedar Hill,UGDS_UNKN,NaN
67805,Strayer University-North Dallas,UGDS_UNKN,NaN
67806,Strayer University-San Antonio,UGDS_UNKN,NaN
67807,Strayer University-Stafford,UGDS_UNKN,NaN
67808,WestMed College - Merced,UGDS_UNKN,NaN
67809,Vantage College,UGDS_UNKN,NaN
67810,SAE Institute of Technology San Francisco,UGDS_UNKN,NaN
67811,Rasmussen College - Overland Park,UGDS_UNKN,NaN
67812,National Personal Training Institute of Cleveland,UGDS_UNKN,NaN
67813,Bay Area Medical Academy - San Jose Satellite ...,UGDS_UNKN,NaN
67814,Excel Learning Center-San Antonio South,UGDS_UNKN,NaN

In [20]:
# 6. pivot 메서드를 사용해 앞 결과를 되돌린다. 

melted_inv = college_melted.pivot(index = 'INSTNM',
                                 columns = 'Race', 
                                 values = 'Percentage')
melted_inv.head()

Race,UGDS_2MOR,UGDS_AIAN,UGDS_ASIAN,UGDS_BLACK,UGDS_HISP,UGDS_NHPI,UGDS_NRA,UGDS_UNKN,UGDS_WHITE
INSTNM,,,,,,,,,
A & W Healthcare Educators,0.0000,0.0,0.0000,0.9750,0.0250,0.0,0.0000,0.0000,0.0000
A T Still University of Health Sciences,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABC Beauty Academy,0.0000,0.0,0.9333,0.0333,0.0333,0.0,0.0000,0.0000,0.0000
ABC Beauty College Inc,0.0000,0.0,0.0000,0.6579,0.0526,0.0,0.0000,0.0000,0.2895
AI Miami International University of Art and Design,0.0018,0.0,0.0018,0.0198,0.4773,0.0,0.0025,0.4644,0.0324

In [33]:
# 7. 기관명이 인덱스 사이를 왔다 갔다 하는 사이 순서가 달라진 점에 주목하자. 
# 열 이름이 원래의 순서가 아니다. 단계 4에서 시작할 때의 DataFrame 을 정확히 복제하려면 .
# .loc 인덱스 연산자를 사용해 행과 열을 동시에 선택하고 인덱스를 리셋해야 한다.

college2_replication = melted_inv.loc[college2['INSTNM'],
                                     college2.columns[1:]].reset_index()
print(college2.equals(college2_replication))
college2_replication

True

,INSTNM,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
0,Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
1,University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
2,Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
3,University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
4,Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137
5,The University of Alabama,0.7825,0.1119,0.0348,0.0106,0.0038,0.0009,0.0261,0.0268,0.0026
6,Central Alabama Community College,0.7255,0.2613,0.0044,0.0025,0.0044,0.0000,0.0000,0.0000,0.0019
7,Athens State University,0.7823,0.1200,0.0191,0.0053,0.0157,0.0010,0.0174,0.0057,0.0334
8,Auburn University at Montgomery,0.5328,0.3376,0.0074,0.0221,0.0044,0.0016,0.0297,0.0397,0.0246
9,Auburn University,0.8507,0.0704,0.0248,0.0227,0.0074,0.0000,0.0000,0.0100,0.0140
10,Birmingham Southern College,0.7983,0.1102,0.0195,0.0517,0.0102,0.0000,0.0051,0.0000,0.0051
11,Chattahoochee Valley Community College,0.4661,0.4372,0.0492,0.0127,0.0023,0.0035,0.0151,0.0000,0.0139
12,Concordia College Alabama,0.0280,0.8758,0.0373,0.0093,0.0000,0.0000,0.0031,0.0466,0.0000
13,South University-Montgomery,0.3046,0.6054,0.0153,0.0153,0.0153,0.0096,0.0000,0.0019,0.0326
14,Enterprise State Community College,0.6408,0.2435,0.0509,0.0202,0.0081,0.0029,0.0254,0.0012,0.0069
15,James H Faulkner State Community College,0.6979,0.2259,0.0320,0.0084,0.0177,0.0014,0.0152,0.0007,0.0009
16,Faulkner University,0.3874,0.5137,0.0258,0.0042,0.0063,0.0013,0.0173,0.0182,0.0258
17,Gadsden State Community College,0.6921,0.2076,0.0305,0.0047,0.0128,0.0018,0.0185,0.0150,0.0169
18,New Beginning College of Cosmetology,0.8957,0.0348,0.0696,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
19,George C Wallace State Community College-Dothan,0.6273,0.3240,0.0221,0.0072,0.0049,0.0009,0.0126,0.0000,0.0009
20,George C Wallace State Community College-Hance...,0.8630,0.0612,0.0362,0.0065,0.0089,0.0000,0.0000,0.0059,0.0183
21,George C Wallace State Community College-Selma,0.1956,0.7449,0.0026,0.0040,0.0013,0.0000,0.0033,0.0040,0.0443
22,Herzing University-Birmingham,0.3543,0.5265,0.0166,0.0066,0.0000,0.0000,0.0563,0.0000,0.0397
23,Huntingdon College,0.6388,0.1993,0.0252,0.0078,0.0122,0.0017,0.0261,0.0061,0.0827
24,Heritage Christian University,0.7419,0.1129,0.0484,0.0000,0.0323,0.0161,0.0000,0.0161,0.0323
25,J F Drake State Community and Technical College,0.3337,0.5965,0.0246,0.0082,0.0113,0.0010,0.0185,0.0000,0.0062
26,Jacksonville State University,0.6834,0.2382,0.0132,0.0055,0.0072,0.0010,0.0000,0.0234,0.0280
27,Jefferson Davis Community College,0.5857,0.2982,0.0077,0.0252,0.0252,0.0000,0.0184,0.0000,0.0397
28,Jefferson State Community College,0.6696,0.2246,0.0486,0.0183,0.0024,0.0008,0.0301,0.0054,0.0001
29,John C Calhoun State Community College,0.6528,0.1940,0.0435,0.0257,0.0182,0.0006,0.0428,0.0062,0.0162
...,...,...,...,...,...,...,...,...,...,...
7505,Strayer University-Lawrenceville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7506,Strayer University-Piscataway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7507,Utah County Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7508,L'esprit Academy - Royal Oak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7509,National Career Institute - Jersey City Branch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7510,Strayer University-Cobb Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7511,Strayer University-Morrow Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7512,Strayer University-Roswell Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7513,Strayer University-Douglasville Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7514,Strayer University-Lithonia Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7515,Strayer University-Savannah Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7516,Strayer University-Augusta Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7517,Strayer University-Columbus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7518,Strayer University-Columbia Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7519,Strayer University-Charleston Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7520,Strayer University-Irving,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7521,Strayer University-Katy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7522,Strayer University-Northwest Houston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7523,Strayer University-Plano,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7524,Strayer University-Cedar Hill,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7525,Strayer University-North Dallas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7526,Strayer University-San Antonio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7527,Strayer University-Stafford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7528,WestMed College - Merced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7529,Vantage College,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7530,SAE Institute of Technology San Francisco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7531,Rasmussen College - Overland Park,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7532,National Personal Training Institute of Cleveland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7533,Bay Area Medical Academy - San Jose Satellite ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7534,Excel Learning Center-San Antonio South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 작동와 원리 

단계 1의 결과를 성취할 수 있는 여러 방법이 있다. 여기서는 read_csv 함수의 유용성을 볼 수 있었다. usecols 매개변수는 임포트하려는 열 이름을 받아들이거나 이를 동적으로 결정하는 함수를 받아들인다. 여기서는 열 이름이 UGDS 를 포함하거나 INCTNM 와 같은 지를 확인하는 익명의 함수를 사용한다. 함수는 각 열 이름이 문자열로 전달되고 불리언을 반환해야 한다. 이 방법을 사용하면 대량의 메모리를 절약할 수 있다. 

단계 2에서 사용한 stack 메서드는 모든 열 이름을 가장 안쪽의 인덱스 레벨에 넣은 후 Series 를 반환한다. 단계 3에서 unstack 메서드는 가장 안쪽 인덱스 레벨의 값을 열 이름으로 변환함으로써 이 연산을 되돌린다. 

단계 4는 단계 1과 동일한 데이터셋을 읽어들이지만 기관명이 인덱스에 들어있지 않으면 melt 메서드가 접근할 수 없기 때문이다. 단계 5는 melt 메서드를 이용해 Race열을 모두 전치한다. 전치하는 방법은 value_vars 매개변수를 그 디폴트 값인 None 으로 두면 된다. 이 값이 지정되지 않으면 id_vars 에 있지 않은 모든 열은 전치된다. 

단계 6은 단계 5로의 연산들